[package]
org = "wso2healthcare"
name = "SmartConfigAPI"
version = "1.0.2"
export = ["SmartConfigAPI.config","SmartConfigAPI.constants","SmartConfigAPI.handlers","SmartConfigAPI.models"]
distribution = "2201.7.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","SMART"]

[build-options]
observabilityIncluded = true
