[package]
org = "wso2healthcare"
name = "MetadataAPI"
version = "1.0.2"
export = ["MetadataAPI.config","MetadataAPI.constants","MetadataAPI.handlers","MetadataAPI.models","MetadataAPI.samples"]
distribution = "2201.7.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Metadata"]

[build-options]
observabilityIncluded = true
